import * as path from 'node:path';

/**
 * Finds what a build generated inside the project folder (in-source qmake builds) so that
 * "Clean Project Build" can delete it. Pure: the file system comes in as `CleanFs`. No `vscode` import.
 * Paths in the plan are relative to the project folder, with `/` separators.
 */

export type EntryKind = 'file' | 'dir' | 'symlink' | 'none';

export interface CleanFs {
  /** Names in a directory (absolute path); empty when it cannot be read. */
  list(dir: string): string[];
  /** What the path is, without following a symlink at its last component. */
  kind(p: string): EntryKind;
  /** The first `bytes` bytes as text; empty when unreadable. */
  readHead(file: string, bytes: number): string;
}

export interface CleanEntry {
  path: string;
  kind: 'file' | 'dir';
}

export interface CleanPlan {
  entries: CleanEntry[];
}

/** Directories the scan never enters. */
const SKIPPED_DIRS = new Set(['.git']);
/** The sfdk output directories at the project root. */
export const OUTPUT_DIRS = ['RPMS', 'BUILD', 'BUILDROOT'];
const QMAKE_HEADER_RE = /Generated by qmake/;
const MAKEFILE_RE = /^Makefile(\..+)?$/;
const MAKEFILE_BYTES = 256 * 1024;
const HEADER_LINES = 5;

/** Names that are qmake/moc/rcc/uic output wherever they sit. */
function isGeneratedFileName(name: string): boolean {
  return (
    name === '.qmake.stash' ||
    name.endsWith('.o') ||
    name.endsWith('.moc') ||
    /^moc_.+\.cpp$/.test(name) ||
    /^qrc_.+\.cpp$/.test(name)
  );
}

/** Names that may sit in a generated directory (OBJECTS_DIR, MOC_DIR, RCC_DIR, UI_DIR) and are safe to delete. */
function isGeneratedInDir(name: string): boolean {
  return isGeneratedFileName(name) || /^ui_.+\.h$/.test(name) || /^moc_.+\.(cpp|h)$/.test(name);
}

/** True when `target` is `root` or below it, judged on the path text. */
export function isInside(root: string, target: string): boolean {
  const rel = path.relative(root, target);
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel));
}

function toRel(root: string, abs: string): string {
  return path.relative(root, abs).split(path.sep).join('/');
}

export interface MakefileInfo {
  objectDirs: string[];
  target?: string;
}

/** Whether the first lines say qmake wrote this Makefile. */
export function isQmakeMakefile(head: string): boolean {
  return head.split(/\r?\n/, HEADER_LINES).some((l) => QMAKE_HEADER_RE.test(l));
}

/** OBJECTS_DIR / MOC_DIR / RCC_DIR / UI_DIR and TARGET assignments of a qmake Makefile. */
export function parseMakefile(text: string): MakefileInfo {
  const info: MakefileInfo = { objectDirs: [] };
  for (const line of text.split(/\r?\n/)) {
    const m = /^(OBJECTS_DIR|MOC_DIR|RCC_DIR|UI_DIR|TARGET)\s*=\s*(.*?)\s*$/.exec(line);
    if (!m || !m[2] || m[2].includes('$(')) continue;
    if (m[1] === 'TARGET') {
      info.target = m[2];
    } else {
      info.objectDirs.push(m[2]);
    }
  }
  return info;
}

export function scanProject(root: string, fs: CleanFs): CleanPlan {
  const resolvedRoot = path.resolve(root);
  const files = new Map<string, CleanEntry>();
  const dirs = new Map<string, CleanEntry>();
  const makefiles: string[] = [];

  /** True when no component from the root to `abs` is a symlink, and it stays inside the root. */
  const reachable = (abs: string): boolean => {
    if (!isInside(resolvedRoot, abs)) return false;
    const rel = path.relative(resolvedRoot, abs);
    let cur = resolvedRoot;
    for (const part of rel.split(path.sep).filter(Boolean)) {
      if (SKIPPED_DIRS.has(part)) return false;
      cur = path.join(cur, part);
      if (fs.kind(cur) === 'symlink') return false;
    }
    return true;
  };

  const addFile = (abs: string): void => {
    if (abs === resolvedRoot || !reachable(abs) || fs.kind(abs) !== 'file') return;
    const rel = toRel(resolvedRoot, abs);
    files.set(rel, { path: rel, kind: 'file' });
  };

  const walk = (dir: string): void => {
    for (const name of fs.list(dir).sort()) {
      const abs = path.join(dir, name);
      const kind = fs.kind(abs);
      if (kind === 'symlink' || kind === 'none') continue;
      if (kind === 'dir') {
        if (!SKIPPED_DIRS.has(name)) walk(abs);
        continue;
      }
      if (MAKEFILE_RE.test(name)) {
        if (isQmakeMakefile(fs.readHead(abs, 1024))) {
          makefiles.push(abs);
          addFile(abs);
        }
      } else if (isGeneratedFileName(name)) {
        addFile(abs);
      }
    }
  };
  walk(resolvedRoot);

  for (const makefile of makefiles) {
    const dir = path.dirname(makefile);
    const info = parseMakefile(fs.readHead(makefile, MAKEFILE_BYTES));
    for (const od of info.objectDirs) {
      const abs = path.resolve(dir, od);
      // Never the project folder itself, and never a folder that holds the project (`..`).
      if (abs === resolvedRoot || !isInside(resolvedRoot, abs) || !reachable(abs) || fs.kind(abs) !== 'dir') continue;
      markGeneratedDir(abs);
    }
    if (info.target) {
      const abs = path.resolve(dir, info.target);
      addFile(abs);
    }
  }

  /** The whole directory when it holds nothing but generated files, else only those files. */
  function markGeneratedDir(abs: string): void {
    const inside: string[] = [];
    let onlyGenerated = true;
    const visit = (d: string): void => {
      for (const name of fs.list(d)) {
        const child = path.join(d, name);
        const kind = fs.kind(child);
        if (kind === 'dir') visit(child);
        else if (kind === 'file' && isGeneratedInDir(name)) inside.push(child);
        else onlyGenerated = false; // a symlink or any other file: not ours to remove wholesale
      }
    };
    visit(abs);
    if (onlyGenerated) {
      const rel = toRel(resolvedRoot, abs);
      dirs.set(rel, { path: rel, kind: 'dir' });
    } else {
      for (const f of inside) addFile(f);
    }
  }

  for (const name of OUTPUT_DIRS) {
    const abs = path.join(resolvedRoot, name);
    if (fs.kind(abs) === 'dir') dirs.set(name, { path: name, kind: 'dir' });
  }

  // Entries below a directory that goes as a whole are not listed again.
  const dirPaths = [...dirs.keys()];
  const covered = (p: string): boolean => dirPaths.some((d) => p === d || p.startsWith(`${d}/`));
  const entries = [
    ...[...dirs.values()].filter((e) => !dirPaths.some((d) => d !== e.path && e.path.startsWith(`${d}/`))),
    ...[...files.values()].filter((e) => !covered(e.path)),
  ].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return { entries };
}

/** The modal text: counts and the first paths, directories with a trailing `/`. */
export function confirmationMessage(projectName: string, plan: CleanPlan, maxPaths = 10): string {
  const n = plan.entries.length;
  const shown = plan.entries.slice(0, maxPaths).map((e) => (e.kind === 'dir' ? `${e.path}/` : e.path));
  const more = n > maxPaths ? `, … and ${n - maxPaths} more` : '';
  return `Clean Project Build will delete ${n} generated ${n === 1 ? 'item' : 'items'} in ${projectName}: ${shown.join(', ')}${more}.`;
}
