import * as assert from 'node:assert';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { describe, it } from 'mocha';
import {
  confirmationMessage,
  isInside,
  isQmakeMakefile,
  parseMakefile,
  scanProject,
  type CleanFs,
  type EntryKind,
} from '../../../src/tasks/cleanCore';
import { applyCleanPlan, nodeCleanFs } from '../../../src/tasks/cleanFs';

const ROOT = '/work/proj';
const QMAKE = '###\n# Makefile for building: demo\n# Generated by qmake (3.1) (Qt 5.6.3)\n';

/** An in-memory file system: path -> kind, files -> content. */
function memFs(entries: Record<string, string>): CleanFs {
  const kinds = new Map<string, EntryKind>();
  const content = new Map<string, string>();
  for (const [p, v] of Object.entries(entries)) {
    const abs = path.posix.join(ROOT, p.replace(/\/$/, ''));
    if (v === 'dir' || v === 'symlink' || v === 'file') {
      kinds.set(abs, v);
    } else {
      kinds.set(abs, 'file');
      content.set(abs, v);
    }
    // parents are dirs
    let parent = path.posix.dirname(abs);
    while (parent.length > 1 && !kinds.has(parent)) {
      kinds.set(parent, 'dir');
      parent = path.posix.dirname(parent);
    }
  }
  return {
    list: (dir) => [...kinds.keys()].filter((k) => path.posix.dirname(k) === dir).map((k) => path.posix.basename(k)),
    kind: (p) => kinds.get(p) ?? 'none',
    readHead: (f, n) => (content.get(f) ?? '').slice(0, n),
  };
}

const paths = (fs: CleanFs): string[] => scanProject(ROOT, fs).entries.map((e) => (e.kind === 'dir' ? `${e.path}/` : e.path));

describe('cleanCore parsing', () => {
  it('recognises the qmake header within the first lines only', () => {
    assert.ok(isQmakeMakefile(QMAKE));
    assert.ok(!isQmakeMakefile('all:\n\techo\n'));
    assert.ok(!isQmakeMakefile('\n\n\n\n\n\n# Generated by qmake'));
  });

  it('reads the dirs and the target, skipping make variables', () => {
    const info = parseMakefile('OBJECTS_DIR   = .obj/\nMOC_DIR       = $(OBJ)\nRCC_DIR=rcc\nUI_DIR = ./\nTARGET        = harbour-demo\n');
    assert.deepStrictEqual(info, { objectDirs: ['.obj/', 'rcc', './'], target: 'harbour-demo' });
  });

  it('judges containment on the path', () => {
    assert.ok(isInside('/a/b', '/a/b/c'));
    assert.ok(isInside('/a/b', '/a/b'));
    assert.ok(!isInside('/a/b', '/a/bc'));
    assert.ok(!isInside('/a/b', '/a/b/../c'.replace('/b/..', '/b/../..')));
    assert.ok(!isInside('/a/b', '/a'));
  });
});

describe('scanProject', () => {
  it('finds generated Makefiles, objects, moc/qrc output, stash and the sfdk dirs', () => {
    const f = memFs({
      Makefile: QMAKE,
      'Makefile.other': QMAKE,
      'main.o': 'file',
      'src/moc_foo.cpp': 'file',
      'src/foo.moc': 'file',
      'qrc_res.cpp': 'file',
      '.qmake.stash': 'file',
      'src/main.cpp': 'file',
      RPMS: 'dir',
      'RPMS/a.rpm': 'file',
      BUILD: 'dir',
      BUILDROOT: 'dir',
    });
    assert.deepStrictEqual(paths(f), [
      '.qmake.stash',
      'BUILD/',
      'BUILDROOT/',
      'Makefile',
      'Makefile.other',
      'RPMS/',
      'main.o',
      'qrc_res.cpp',
      'src/foo.moc',
      'src/moc_foo.cpp',
    ]);
  });

  it('keeps a hand-written Makefile', () => {
    const f = memFs({ Makefile: 'all:\n\tgcc main.c\n', 'Makefile.dist': '# my own\nall:\n' });
    assert.deepStrictEqual(paths(f), []);
  });

  it('deletes an object directory named in a generated Makefile as a whole when it holds only generated files', () => {
    const f = memFs({
      Makefile: `${QMAKE}OBJECTS_DIR   = .obj-jpeg/\nMOC_DIR = .obj-jpeg/\n`,
      '.obj-jpeg/a.o': 'file',
      '.obj-jpeg/moc_x.cpp': 'file',
      '.obj-jpeg/sub/b.o': 'file',
    });
    assert.deepStrictEqual(paths(f), ['.obj-jpeg/', 'Makefile']);
  });

  it('removes only the generated files of a referenced directory that also holds other files', () => {
    const f = memFs({
      Makefile: `${QMAKE}OBJECTS_DIR = src/\n`,
      'src/a.o': 'file',
      'src/a.cpp': 'file',
    });
    assert.deepStrictEqual(paths(f), ['Makefile', 'src/a.o']);
  });

  it('ignores a directory outside the project, the project itself and a parent', () => {
    const f = memFs({
      Makefile: `${QMAKE}OBJECTS_DIR = ../other/\nMOC_DIR = ./\nRCC_DIR = ..\nUI_DIR = /etc/\n`,
      'main.cpp': 'file',
    });
    assert.deepStrictEqual(paths(f), ['Makefile']);
  });

  it('deletes the qmake TARGET binary when it is a file inside the project', () => {
    const f = memFs({ Makefile: `${QMAKE}TARGET = harbour-demo\n`, 'harbour-demo': 'file' });
    assert.deepStrictEqual(paths(f), ['Makefile', 'harbour-demo']);
  });

  it('never takes a TARGET outside the project or a TARGET that is a directory', () => {
    const outside = memFs({ Makefile: `${QMAKE}TARGET = ../evil\n` });
    assert.deepStrictEqual(paths(outside), ['Makefile']);
    const dir = memFs({ Makefile: `${QMAKE}TARGET = src\n`, 'src/x.cpp': 'file' });
    assert.deepStrictEqual(paths(dir), ['Makefile']);
  });

  it('does not follow or list symlinks', () => {
    const f = memFs({
      Makefile: `${QMAKE}OBJECTS_DIR = link/\nTARGET = tlink\n`,
      link: 'symlink',
      tlink: 'symlink',
      'linked.o': 'symlink',
      RPMS: 'symlink',
    });
    assert.deepStrictEqual(paths(f), ['Makefile']);
  });

  it('does not descend into a symlinked directory or reach through one', () => {
    const f = memFs({
      linkdir: 'symlink',
      'linkdir/x.o': 'file',
      Makefile: `${QMAKE}OBJECTS_DIR = linkdir/obj/\n`,
      'linkdir/obj/a.o': 'file',
    });
    assert.deepStrictEqual(paths(f), ['Makefile']);
  });

  it('leaves .git untouched', () => {
    const f = memFs({
      '.git/objects/x.o': 'file',
      '.git/Makefile': QMAKE,
      Makefile: `${QMAKE}OBJECTS_DIR = .git/\n`,
    });
    assert.deepStrictEqual(paths(f), ['Makefile']);
  });

  it('lists a directory once, not its files', () => {
    const f = memFs({ Makefile: `${QMAKE}OBJECTS_DIR = BUILD/\n`, 'BUILD/a.o': 'file' });
    assert.deepStrictEqual(paths(f), ['BUILD/', 'Makefile']);
  });

  it('only the root level holds sfdk output dirs', () => {
    const f = memFs({ 'sub/RPMS/a.rpm': 'file' });
    assert.deepStrictEqual(paths(f), []);
  });
});

describe('confirmationMessage', () => {
  it('lists counts and the first paths', () => {
    const entries = Array.from({ length: 12 }, (_, i) => ({ path: `f${i}.o`, kind: 'file' as const }));
    entries.unshift({ path: '.obj', kind: 'dir' as never });
    const text = confirmationMessage('RAWfish', { entries });
    assert.ok(text.startsWith('Clean Project Build will delete 13 generated items in RAWfish: .obj/, f0.o'), text);
    assert.ok(text.endsWith('… and 3 more.'), text);
  });

  it('uses the singular for one item', () => {
    assert.strictEqual(
      confirmationMessage('P', { entries: [{ path: 'Makefile', kind: 'file' }] }),
      'Clean Project Build will delete 1 generated item in P: Makefile.',
    );
  });
});

describe('applyCleanPlan on a real folder', () => {
  function tmp(): string {
    return fs.mkdtempSync(path.join(os.tmpdir(), 'sf-clean-'));
  }

  it('scans and deletes generated files, keeps sources, and never follows a symlink out of the folder', () => {
    const root = tmp();
    const outside = tmp();
    try {
      fs.writeFileSync(path.join(outside, 'precious.o'), 'x');
      fs.writeFileSync(path.join(root, 'Makefile'), `${QMAKE}OBJECTS_DIR = .obj/\nTARGET = demo\n`);
      fs.mkdirSync(path.join(root, '.obj'));
      fs.writeFileSync(path.join(root, '.obj', 'a.o'), '');
      fs.writeFileSync(path.join(root, 'demo'), '');
      fs.writeFileSync(path.join(root, 'main.cpp'), 'int main(){}');
      fs.symlinkSync(outside, path.join(root, 'out-link'));
      fs.mkdirSync(path.join(root, '.git'));
      fs.writeFileSync(path.join(root, '.git', 'x.o'), '');
      fs.mkdirSync(path.join(root, 'RPMS'));

      const plan = scanProject(root, nodeCleanFs);
      const logged: string[] = [];
      const result = applyCleanPlan(root, plan, (p) => logged.push(p));
      assert.deepStrictEqual(result.failed, []);
      assert.deepStrictEqual(logged.sort(), ['.obj', 'Makefile', 'RPMS', 'demo']);
      assert.ok(fs.existsSync(path.join(root, 'main.cpp')));
      assert.ok(fs.existsSync(path.join(root, '.git', 'x.o')));
      assert.ok(fs.existsSync(path.join(outside, 'precious.o')));
      assert.ok(fs.lstatSync(path.join(root, 'out-link')).isSymbolicLink());
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
      fs.rmSync(outside, { recursive: true, force: true });
    }
  });

  it('refuses plan entries outside the folder or in .git', () => {
    const root = tmp();
    const outside = tmp();
    try {
      fs.writeFileSync(path.join(outside, 'a.o'), '');
      fs.mkdirSync(path.join(root, '.git'));
      fs.writeFileSync(path.join(root, '.git', 'a.o'), '');
      const result = applyCleanPlan(root, {
        entries: [
          { path: `../${path.basename(outside)}/a.o`, kind: 'file' },
          { path: '.git/a.o', kind: 'file' },
          { path: '.', kind: 'dir' },
        ],
      });
      assert.strictEqual(result.deleted.length, 0);
      assert.strictEqual(result.failed.length, 3);
      assert.ok(fs.existsSync(path.join(outside, 'a.o')));
      assert.ok(fs.existsSync(path.join(root, '.git', 'a.o')));
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
      fs.rmSync(outside, { recursive: true, force: true });
    }
  });

  it('refuses an entry that turned into a symlink after the scan', () => {
    const root = tmp();
    const outside = tmp();
    try {
      fs.symlinkSync(outside, path.join(root, 'RPMS'));
      const result = applyCleanPlan(root, { entries: [{ path: 'RPMS', kind: 'dir' }] });
      assert.strictEqual(result.failed.length, 1);
      assert.ok(fs.existsSync(outside));
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
      fs.rmSync(outside, { recursive: true, force: true });
    }
  });
});
