import * as assert from 'assert';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as vscode from 'vscode';
import { extensionApi, stubMessages, waitForContext } from './helpers';
import type { BuildTreeDataProvider } from '../../src/build/buildView';
import type { Services } from '../../src/core/services';

/** Build view and Clean Project Build; only discovered when TEST_MODE != 'bare'. Plain structural checks, no `instanceof`. */

interface Api {
  __test: { getServices: () => Services; getBuildView: () => BuildTreeDataProvider };
}

function api(): Api {
  return extensionApi() as unknown as Api;
}

function folder(): vscode.WorkspaceFolder {
  const f = vscode.workspace.workspaceFolders?.[0];
  if (!f) throw new Error('expected a workspace folder (qml-app fixture)');
  return f;
}

suite('Build view and Clean Project Build', () => {
  test('the Build view lists target, device, type, deploy, signing and last build', async () => {
    await waitForContext('sardina.isProject', true, 8000);
    const rows = api().__test.getBuildView().getChildren() as vscode.TreeItem[];
    assert.deepStrictEqual(
      rows.map((r) => r.id),
      ['project', 'target', 'device', 'type', 'deploy', 'signing', 'last'],
    );
    const command = (id: string): string | undefined => rows.find((r) => r.id === id)?.command?.command;
    assert.strictEqual(command('target'), 'sardina.selectTarget');
    assert.strictEqual(command('device'), 'sardina.device.setDefault');
    assert.strictEqual(command('type'), 'sardina.selectBuildType');
    assert.strictEqual(command('deploy'), 'sardina.selectDeployMethod');
    assert.strictEqual(command('signing'), 'sardina.setupSigning');
    assert.strictEqual(command('last'), 'sardina.showBuildLog');
    // Earlier suites run builds against the fake sfdk, so the shared build state may already hold a result.
    const last = rows.find((r) => r.id === 'last')?.description ?? '';
    const lastText = String(last);
    assert.match(lastText, /^(idle|[✓✗■] (succeeded|failed|stopped) .+)$/, lastText);
  });

  test('Clean Project Build deletes generated files and dirs after a confirmation, and keeps sources', async () => {
    await waitForContext('sardina.isProject', true, 8000);
    const root = folder().uri.fsPath;
    const makefile = path.join(root, 'Makefile');
    const objDir = path.join(root, '.obj-test');
    const handWritten = path.join(root, 'Makefile.hand');
    const messages = stubMessages();
    messages.chosenAction = 'Delete';
    try {
      fs.writeFileSync(makefile, '#############################################################################\n# Makefile for building: demo\n# Generated by qmake (3.1) (Qt 5.6.3) on: Mon Oct 6 2026\n\nOBJECTS_DIR   = .obj-test/\nTARGET        = demo-bin\n');
      fs.mkdirSync(objDir);
      fs.writeFileSync(path.join(objDir, 'main.o'), '');
      fs.writeFileSync(handWritten, 'all:\n\techo hi\n');
      await vscode.commands.executeCommand('sardina.cleanProjectBuild');
      assert.ok(!fs.existsSync(makefile), 'generated Makefile is deleted');
      assert.ok(!fs.existsSync(objDir), 'object dir is deleted');
      assert.ok(fs.existsSync(handWritten), 'a hand-written Makefile is kept');
      const modal = messages.calls.find((c) => c.kind === 'warning' && c.message.startsWith('Clean Project Build will delete'));
      assert.ok(modal, 'a confirmation was shown');
      assert.ok(modal.message.includes('Makefile') && modal.message.includes('.obj-test/'), modal.message);
    } finally {
      fs.rmSync(makefile, { force: true });
      fs.rmSync(objDir, { recursive: true, force: true });
      fs.rmSync(handWritten, { force: true });
    }
  });
});
